# Generated by Django 2.1.1 on 2019-08-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=300)),
                ('civil_status', models.CharField(max_length=50)),
                ('partner_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=14)),
                ('monthly_income', models.BigIntegerField(default=0)),
            ],
        ),
    ]
