# Generated by Django 2.1.1 on 2019-08-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='partner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
