# Generated by Django 2.1.1 on 2019-08-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190811_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=40)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=40)),
                ('interest', models.DecimalField(decimal_places=4, max_digits=40)),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=40)),
                ('loan_period', models.IntegerField(default=0)),
                ('loan_witness', models.CharField(max_length=200)),
                ('cbu', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('clustername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanapplications', to='api.ClusterName')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanapplications', to='api.Member')),
            ],
        ),
        migrations.CreateModel(
            name='LoanSchedulePayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('principal', models.DecimalField(decimal_places=4, max_digits=40)),
                ('interest', models.DecimalField(decimal_places=4, max_digits=40)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanscheds', to='api.Loan')),
            ],
        ),
    ]
