# Generated by Django 2.1.1 on 2019-08-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_loan_loanschedulepayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='percentage',
            new_name='interest_rate',
        ),
    ]
