# Generated by Django 2.1.1 on 2019-08-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190813_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
