# Generated by Django 2.1.1 on 2019-08-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_loan_date_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_release',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
