# Generated by Django 2.1.1 on 2019-08-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190818_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
