# Generated by Django 2.1.1 on 2019-08-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190818_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_release',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loanschedulepayments',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
