# Generated by Django 2.1.1 on 2019-08-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190818_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanschedulepayments',
            name='date',
            field=models.DateField(),
        ),
    ]
