# Generated by Django 2.1.1 on 2019-08-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_loanpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loan',
            name='payment_period',
            field=models.IntegerField(default=1),
        ),
    ]
