# Generated by Django 2.1.1 on 2019-08-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190821_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanschedulepayments',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
        migrations.AlterField(
            model_name='loanschedulepayments',
            name='principal',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
    ]
