# Generated by Django 2.1.1 on 2019-08-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190821_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
