# Generated by Django 2.1.1 on 2019-08-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_member_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_cycle',
            field=models.IntegerField(default=1),
        ),
    ]
