# Generated by Django 2.1.1 on 2019-08-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190823_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_mode',
            field=models.IntegerField(default=1),
        ),
    ]
