# Generated by Django 2.1.1 on 2019-08-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_loan_loan_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='clustername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loanapplications', to='api.ClusterName'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loanapplications', to='api.Member'),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loanpayments', to='api.Loan'),
        ),
    ]
