# Generated by Django 2.1.1 on 2019-08-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190823_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_period',
            field=models.FloatField(default=0.0),
        ),
    ]
